import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';
import { Suspense, SuspenseProps, useEffect, useState } from 'react';

const GameNoSSR = dynamic(() => import('../game/Game'), { ssr: false });

const SuspensePostHydration = function (props: SuspenseProps): JSX.Element {
  const [postHydration, setPostHydration] = useState(false);
  useEffect(() => {
    setPostHydration(true);
  }, []);
  return postHydration ? <Suspense {...props} /> : <></>;
};

const PostHydration = function (
  props: { children: () => React.ReactElement },
): JSX.Element {
  const [postHydration, setPostHydration] = useState(false);
  useEffect(() => {
    setPostHydration(true);
  }, []);
  return postHydration ? props.children() : <></>;
};

function MaybeFullscreenButton() {
  const [isFullscreen, setFullscreen] = useState(false);
  if (!Boolean(document.body.requestFullscreen)) {
    return <></>;
  }
  return (
    <>
      {!isFullscreen && (
        <button
          onClick={() =>
            document.body.requestFullscreen().then(() => setFullscreen(true))}
        >
          fullscreen
        </button>
      )}
      {isFullscreen && (
        <button
          onClick={() =>
            document.exitFullscreen().then(() => setFullscreen(false))}
        >
          leave fullscreen
        </button>
      )}
    </>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <PostHydration>
          {() => <MaybeFullscreenButton />}
        </PostHydration>
        <SuspensePostHydration
          fallback={<h1>loading...</h1>}
        >
          <GameNoSSR />
        </SuspensePostHydration>
      </main>
    </div>
  );
};

export default Home;
