#! /bin/bash
cd "$(dirname "$0")"
cd "$(git rev-parse --show-toplevel)"/front-end

set -e -x

shopt -s extglob
GLOBIGNORE='node_modules/*'
deno fmt --options-single-quote *.ts?(x) **/*.ts?(x)
npm run lint -- --fix
